<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kiyote.Buffers" />
    <PackageReference Include="Kiyote.Geometry" />
    <PackageReference Include="Kiyote.Imaging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Kiyote\Mathematics\Kiyote.Mathematics\Kiyote.Mathematics.csproj" />
  </ItemGroup>

</Project>
